AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    83453b04-7644-4097-9f67-f65cd55e29a4:
      size:
        width: 1470
        height: 870
      position:
        x: 30
        'y': 240
      z: 1
      embeds:
        - cf4abe3e-4e86-419c-ba19-30e77b475d89
        - f17fb5a9-9ee5-493e-bfd7-0ecd88a9d6fc
        - 7956d3bf-0411-47c3-a791-53af78c3db0e
        - 505abc1b-744b-4f1c-ac1d-4593ee0c8f7d
        - 6ffe7d8f-706d-477c-abb6-5804e99061fe
        - df4a2a8d-57ec-470f-9d4b-2fe143094311
    505abc1b-744b-4f1c-ac1d-4593ee0c8f7d:
      size:
        width: 900
        height: 300
      position:
        x: 480
        'y': 270
      z: 2
      parent: 83453b04-7644-4097-9f67-f65cd55e29a4
      embeds:
        - 233f632d-b924-4fdf-b4a4-0e5876a405d3
        - 00b8a74f-7587-43c3-a659-60ef9014da8a
      iscontainedinside:
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
    7956d3bf-0411-47c3-a791-53af78c3db0e:
      size:
        width: 900
        height: 300
      position:
        x: 480
        'y': 600
      z: 2
      parent: 83453b04-7644-4097-9f67-f65cd55e29a4
      embeds:
        - 5265c801-0cd5-458e-8219-b108dd48d189
        - 2a658f03-e462-422f-b8d8-6abc59b74be2
      iscontainedinside:
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
    df4a2a8d-57ec-470f-9d4b-2fe143094311:
      size:
        width: 60
        height: 60
      position:
        x: 330
        'y': 540
      z: 2
      parent: 83453b04-7644-4097-9f67-f65cd55e29a4
      embeds: []
      iscontainedinside:
        - 505abc1b-744b-4f1c-ac1d-4593ee0c8f7d
        - 7956d3bf-0411-47c3-a791-53af78c3db0e
    6ffe7d8f-706d-477c-abb6-5804e99061fe:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 540
      z: 2
      parent: 83453b04-7644-4097-9f67-f65cd55e29a4
      embeds: []
    cf4abe3e-4e86-419c-ba19-30e77b475d89:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 540
      z: 2
      parent: 83453b04-7644-4097-9f67-f65cd55e29a4
      embeds: []
    f17fb5a9-9ee5-493e-bfd7-0ecd88a9d6fc:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 300
      z: 2
      parent: 83453b04-7644-4097-9f67-f65cd55e29a4
      embeds: []
      iscontainedinside:
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
        - 83453b04-7644-4097-9f67-f65cd55e29a4
    00b8a74f-7587-43c3-a659-60ef9014da8a:
      size:
        width: 60
        height: 60
      position:
        x: 590
        'y': 330
      z: 3
      parent: 505abc1b-744b-4f1c-ac1d-4593ee0c8f7d
      embeds: []
      iscontainedinside:
        - 505abc1b-744b-4f1c-ac1d-4593ee0c8f7d
        - 505abc1b-744b-4f1c-ac1d-4593ee0c8f7d
    5265c801-0cd5-458e-8219-b108dd48d189:
      size:
        width: 60
        height: 60
      position:
        x: 590
        'y': 660
      z: 3
      parent: 7956d3bf-0411-47c3-a791-53af78c3db0e
      embeds: []
      iscontainedinside:
        - 7956d3bf-0411-47c3-a791-53af78c3db0e
    2a658f03-e462-422f-b8d8-6abc59b74be2:
      size:
        width: 60
        height: 60
      position:
        x: 590
        'y': 780
      z: 3
      parent: 7956d3bf-0411-47c3-a791-53af78c3db0e
      embeds: []
      iscontainedinside:
        - 7956d3bf-0411-47c3-a791-53af78c3db0e
    233f632d-b924-4fdf-b4a4-0e5876a405d3:
      size:
        width: 60
        height: 60
      position:
        x: 590
        'y': 450
      z: 3
      parent: 505abc1b-744b-4f1c-ac1d-4593ee0c8f7d
      embeds: []
      iscontainedinside:
        - 505abc1b-744b-4f1c-ac1d-4593ee0c8f7d
Resources:
  PrivateNet:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: PrivateNet
        - Key: Component
          Value: PrivateNet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 83453b04-7644-4097-9f67-f65cd55e29a4
  PNSubNet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref PrivateNet
      CidrBlock: 10.0.0.0/25
      AvailabilityZone: ap-northeast-1a
      Tags:
        - Key: Name
          Value: PNSubNet1
        - Key: Component
          Value: PrivateNet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 505abc1b-744b-4f1c-ac1d-4593ee0c8f7d
  PNSubNet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref PrivateNet
      CidrBlock: 10.0.0.128/25
      AvailabilityZone: ap-northeast-1c
      Tags:
        - Key: Name
          Value: PNSubNet2
        - Key: Component
          Value: PrivateNet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7956d3bf-0411-47c3-a791-53af78c3db0e
  PNELB:
    Type: 'AWS::ElasticLoadBalancing::LoadBalancer'
    Properties:
      LoadBalancerName: PNELB
      Scheme: internal
      Subnets:
        - !Ref PNSubNet1
        - !Ref PNSubNet2
      Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '80'
          Protocol: HTTP
          InstanceProtocol: HTTP
      Tags:
        - Key: Name
          Value: PNELB
        - Key: Component
          Value: PrivateNet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: df4a2a8d-57ec-470f-9d4b-2fe143094311
  PNRoleToELB:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: PNELBFullAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: cf4abe3e-4e86-419c-ba19-30e77b475d89
  GetBalance:
    Type: 'AWS::Lambda::Function'
    Properties:
      Runtime: python3.6
      Code:
        ZipFile: ./tmp.zip
      Handler: handler.lambda_handler
      Role: !GetAtt PNRoleToELB.Arn
      VpcConfig:
        SecurityGroupIds:
          - !Ref PNSecurityGroup
        SubnetIds:
          - !Ref PNSubNet1
          - !Ref PNSubNet2
      Tags:
        - Key: Name
          Value: GetBalance
        - Key: Component
          Value: PrivateNet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 6ffe7d8f-706d-477c-abb6-5804e99061fe
  PNSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref PrivateNet
      GroupName: PNSecurityGroup
      GroupDescription: Security Gropu for Private net.
      Tags:
        - Key: Name
          Value: PNSecurityGroup
        - Key: Component
          Value: PrivateNet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f17fb5a9-9ee5-493e-bfd7-0ecd88a9d6fc
  PNParityPoA1a:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-bec974d8
      SubnetId: !Ref PNSubNet1
      KeyName: private-net
      Tags:
        - Key: Name
          Value: PNParityPoA1a
        - Key: Component
          Value: PrivateNet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 00b8a74f-7587-43c3-a659-60ef9014da8a
  PNParityPoA2a:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-bec974d8
      SubnetId: !Ref PNSubNet1
      KeyName: private-net
      Tags:
        - Key: Name
          Value: PNParityPoA2a
        - Key: Component
          Value: PrivateNet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 233f632d-b924-4fdf-b4a4-0e5876a405d3
  PNParityPoA1c:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-bec974d8
      SubnetId: !Ref PNSubNet2
      KeyName: private-net
      Tags:
        - Key: Name
          Value: PNParityPoA1c
        - Key: Component
          Value: PrivateNet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 2a658f03-e462-422f-b8d8-6abc59b74be2
  PNParityPoA2c:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-bec974d8 # TODO: Change image to Parity PoA that built by Packer.
      SubnetId: !Ref PNSubNet2
      KeyName: private-net
      Tags:
        - Key: Name
          Value: PNParityPoA2c
        - Key: Component
          Value: PrivateNet
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 5265c801-0cd5-458e-8219-b108dd48d189
