---
- name: Add private key to each hosts
  copy:
    dest: /home/ubuntu/.ssh/private-chain
    owner: ubuntu
    group: ubuntu
    mode: 0600
    content: "{{ lookup('file', '~/.ssh/private-chain') }}"

- name: Copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: ubuntu
    group: ubuntu
    mode: 0644
  with_items:
    - { src: 'config', dest: "/home/ubuntu/.ssh/config" }
