---

- name: Parity configurations and start nodes.
  hosts: parity-poa
  remote_user: ubuntu
  become: yes

  roles:
    - common
    - private-chain

- name: Bastion server configrations.
  hosts: bastion
  remote_user: ubuntu
  become: yes

  roles:
    - common
    - { role: leesoh.pipenv }
    - { role: ChromaticHQ.aws-cli }
    - bastion

